"""Data models and typed contracts for Denver Proactive Intelligence."""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from enum import Enum, unique
from typing import Any


@unique
class SuggestionCategory(str, Enum):
    """Functional categories for autonomous proactive suggestions."""

    HEALTH = "health"
    SYSTEM = "system"
    WORKFLOW = "workflow"
    FATIGUE = "fatigue"
    TASK = "task"
    ROUTINE = "routine"


@unique
class SuggestionPriority(str, Enum):
    """Urgency level of a proactive suggestion."""

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


@dataclass
class ProactiveSuggestion:
    """A context-aware autonomous recommendation generated by Denver."""

    id: str
    category: SuggestionCategory
    priority: SuggestionPriority
    title: str
    message: str
    suggested_action: str | None = None
    suggested_params: dict[str, Any] = field(default_factory=dict)
    created_at: float = field(default_factory=time.time)
    dismissed: bool = False
    accepted: bool = False
    confidence: float = 1.0

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "category": self.category.value,
            "priority": self.priority.value,
            "title": self.title,
            "message": self.message,
            "suggested_action": self.suggested_action,
            "suggested_params": self.suggested_params,
            "created_at": self.created_at,
            "dismissed": self.dismissed,
            "accepted": self.accepted,
            "confidence": self.confidence,
        }


@dataclass
class ProactiveContext:
    """Real-time system, environmental, and behavioral telemetry snapshot."""

    battery_percent: float | None = None
    battery_power_plugged: bool | None = None
    cpu_percent: float | None = None
    memory_percent: float | None = None
    active_window_title: str | None = None
    active_window_process: str | None = None
    continuous_work_seconds: float = 0.0
    pending_tasks_count: int = 0
    pending_tasks_summary: list[str] = field(default_factory=list)
    current_hour: int = field(default_factory=lambda: time.localtime().tm_hour)
